### ISSUE TITLE
can't build under 32 bit architectures

### ISSUE THREAD

**Issue by kenshaw** [tdewolff/font#1]
While trying to do the release for [`fv`](https://github.com/kenshaw/fv), the latest `font` package failed to compile for the `arm` (a 32-bit platform) architecture. This is due to a comparison of a `int` to `math.MaxUint32`. On 32-bit platforms, a `int` will always be the same as `int32`, which causes the build failure:

```sh
$ GOARCH=arm go build
# github.com/tdewolff/font
./sfnt_cff.go:2032:5: math.MaxUint32 (untyped int constant 4294967295) overflows int
```

This can be fixed by changing the compared values to `uint64` or `int64`. 

This is a very minor/trivial issue. In the interest of portability, however, it would be nice if this could be fixed, and I'd be glad to submit a PR for it.

**Comment by tdewolff** [comment]
Thanks Kenneth, thanks for bringing this up. This has been fixed now in master, let me know if it works well!

**Comment by kenshaw** [comment]
@tdewolff Thanks, you're always the consummate professional. Love `canvas`!

**Comment by tdewolff** [comment]
Thanks for the kind words Kenneth, always appreciate your feedback and issues :-D

**Comment by tdewolff** [comment]
Fixed a bug that was introduced in the fix above, please pull from master again.
