### ISSUE TITLE
bad checksum panic

### ISSUE THREAD

**Issue by zpl-zak** [tdewolff/font#5]
Hey, we receive a bad checksum panic with the font file provided below.
[helveticaltstd-cond.zip](https://github.com/user-attachments/files/17868294/helveticaltstd-cond.zip)

Given that we use lots of various fonts, old and new, we are unable to fix the fonts ourselves. We've ended up removing few checks on our end so that the font would continue the parsing process, there might be undesirable side-effects to that but nothing we've noticed so far: https://github.com/tdewolff/font/commit/9187c406532a76b5e3ba2725c815d7c173b7cbd3

**Comment by tdewolff** [comment]
There should be no side-effects from disabling that check. We're not a font file validator, so we should do our best effort of parsing for broken fonts. Thanks for the issue.

**Comment by zpl-zak** [comment]
Hey, we're still hitting the panic at https://github.com/tdewolff/font/commit/39987c37b35f57b0f9e3766fe8042449acf212c4#diff-1d35227fdfaaf6ceb61d0d78c35134cee518033df7944d5a8c2f49a173e65821R289 after this change.

**Comment by tdewolff** [comment]
Ok, I've disabled table checksums as well.
